name: Blank issue
description: Used for tracking work as issues
title: "[Issue]: "
assignees:
  - SWCoE
body:
  - type: textarea
    id: Description
    attributes:
      label: Relevant issues
      description: Please provide necessary details in the text area
      render: text
