name: Blank issue
description: Used for tracking work as issues
title: "[Issue]: "
assignees:
  - SWCoE
body:
body:
- type: input
  id: Input
  attributes:
    label: Input
    description: "What is the expected input?"
    placeholder: "Example: Work with the team to come up with questionnaire for the craft 2.0 modules"
  validations:
    required: false
- type: input
  id: Output
  attributes:
    label: Output
    description: "What is the expected output?"
    placeholder: "Example: Reviewed questionnaire for the craft 2.0 modules"
  validations:
    required: false
- type: input
  id: Size
  attributes:
    label: Size
    description: "What is the approximate task size?"
    placeholder: "Example: Reviewed questionnaire for the craft 2.0 modules"
  validations:
    required: false
