name: Recruitment
description: Used for tracking recruitment specific activities
title: "[Recruitment]: "
labels: ["hiring"]
assignees:
  - SWCoE
body:
  - type: checkboxes
    id: RelatedActivities
    attributes:
      label: Tick all the related activities you intend to get involved in, in this sprint.
      options:
        - label: Resume screening & shortlisting
          required: false
        - label: Vendor management & expectation setting
          required: false
        - label: Talent acquisition interactions
          required: false
        - label: Interview panelist identification & scheduling slots
          required: false
        - label: Interviewing candidates & submitting discussion feedback
          required: false
        - label: Closing the loop with debrief
          required: false
        - label: Working with the HR/TA team on the pre-onboarding needs (CODE1-creation, Equipments etc.)
          required: false
  - type: markdown
    attributes:
      value: |
        ### NOTE: Please ensure that you are assigning this issue to yourself and you are tracking it to its completion. Thank you!
